<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Virens-MacBook-Pro.local" failures="1" tests="6" name="Default test" time="27.463" errors="0" timestamp="2024-01-18T15:36:45 PST">
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC1" time="9.361"/>
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC2" time="3.915"/>
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC3SelectFormate" time="2.218"/>
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC4Customormate" time="2.464">
    <failure type="java.lang.AssertionError" message="expected [Sun Dec 27 00:00:00 PST 5] but found [YYYY-MM-DD]">
      <![CDATA[java.lang.AssertionError: expected [Sun Dec 27 00:00:00 PST 5] but found [YYYY-MM-DD]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:643)
at pages.RandomDateGeneratePage.VerifyGeneratedCustomDateFormat(RandomDateGeneratePage.java:162)
at tests.TC1RandonDateGenerate.RDGTC4Customormate(TC1RandonDateGenerate.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RDGTC4Customormate -->
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC5CustomormateDrp" time="3.092"/>
  <testcase classname="tests.TC1RandonDateGenerate" name="RDGTC6StartEndDate" time="2.823"/>
</testsuite> <!-- Default test -->
